# Generated by Django 3.2.7 on 2021-11-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_streaming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streaming',
            old_name='name',
            new_name='streaming_service',
        ),
    ]
