# Generated by Django 3.2.7 on 2021-11-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_name_streaming_streaming_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='streams',
            field=models.ManyToManyField(to='main_app.Streaming'),
        ),
    ]
